name: Metrics
on:
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          template: repository
          repo: AdventOfCode
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Berlin
          base: "metadata"
          plugin_languages: yes
          plugin_languages_recent_days: 0
          config_order: languages, base.metadata
